### ISSUE TITLE
不更新了吗？

### ISSUE THREAD

**Issue by suncunhu** [axlecho/yiye-android#1]
yiye.me网站挂了，
这个项目不做了吗？

导入AS后报错
Error:(57, 0) Could not find property 'Compile' on com.android.build.gradle.AppExtension_Decorated@75a97e46.
如何解决？

**Comment by suncunhu** [comment]
原来是AS版本的原因，加载.so文件的方式不同

**Comment by axlecho** [comment]
不做了，一叶团队由于毕业解散了
